# Generated by Django 4.2.11 on 2024-04-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("register", "0002_customuser_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_name",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
