# Generated by Django 5.0.3 on 2024-03-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trxn_class",
                    models.CharField(
                        choices=[("debit", "DEBIT"), ("credit", "CREDIT")],
                        max_length=20,
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                (
                    "trxn_type",
                    models.CharField(
                        choices=[
                            ("withdraw", "WITHDRAW"),
                            ("transfer", "TRANSFER"),
                            ("deposit", "DEPOSIT"),
                            ("payment", "PAYMENT"),
                            ("request", "REQUEST"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "PENDING"),
                            ("success", "SUCCESS"),
                            ("failed", "FAILED"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.PositiveIntegerField(default=1000)),
                (
                    "account_type",
                    models.CharField(
                        choices=[("gbp", "GBP"), ("usd", "USD")], max_length=20
                    ),
                ),
            ],
        ),
    ]
