# Generated by Django 4.2.11 on 2024-04-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payapp", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="account_number",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
