# Generated by Django 4.2.11 on 2024-04-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payapp", "0005_alter_transaction_trxn_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="new_balance",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
